export const projects = {
  title: 'Projects',
  wip: 'Work In Progress',
  noCompleted: 'No completed projects yet.',
  completed: 'Completed Projects',
  noCodePenProjects: 'No CodePen projects yet.',
  archived: 'Archived',
  viewProduct: 'View Product',
  codepenTitle: 'CodePen Projects',
  loading: 'Loading projects…',
  noProjects: 'Projects are in progress, check back soon!',
  goToRepo: 'Repository',
  error: 'Failed to load projects. Please try again later.',
  all: 'All',
  liveSite: 'Live Site',
};
