name: Run Prettier

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: prettier-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          persist-credentials: false

      - name: Prettify code
        run: |
          corepack enable
          yarn install --immutable
          yarn prettier
